export enum ErrorCodes {

  // Friend
  FRIEND_DELETION_FAILED = 'FRIEND_DELETION_FAILED',
  FRIEND_NOT_FOUND = 'FRIEND_NOT_FOUND',

  // User
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_UPDATE_FAILED = 'ACCOUNT_UPDATE_FAILED',
  ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR',

  // Session
  USER_SESSION_CREATION_FAILED = 'USER_SESSION_CREATION_FAILED',
  USER_SESSION_INVALID = 'USER_SESSION_INVALID',
  USER_SESSION_UPDATE_FAILED = 'USER_SESSION_UPDATE_FAILED',

  // Generic
  SERVER_EVENT_UNSUPPORTED = 'SERVER_EVENT_UNSUPPORTED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
