load('ext://dotenv', 'dotenv')
dotenv()

# Run core services
docker_compose(
  configPaths="./docker/docker-compose-core.yml",
  env_file=".env",
  project_name="dsc-demo",
  wait=True
)
dc_resource('mongodb', labels=['core'])

# Setup
local_resource(
  name = "Yarn Install",
  cmd = "yarn install",
  labels=['setup'],
  allow_parallel=True,
)

# Run Services
local_resource(
  name="main",
  serve_cmd="yarn nx run main:serve --configuration=development",
  allow_parallel=True,
  serve_env={
    "NAME": os.getenv('NAME', 'main-api'),
    "PRODUCTION_FEATURES": os.getenv('PRODUCTION_FEATURES', 'true'),
    "ENVIRONMENT_NAME":  os.getenv('ENVIRONMENT_NAME', 'development'),

    # Database
    "MONGO_CONNECTION_STRING": "mongodb://localhost:27017/dsc-demo?directConnection=true",
    "MONGO_DATABASE_NAME": "dsc-demo",
  },
  labels=['services'],
  resource_deps=['mongodb', 'Yarn Install']
)

local_resource(
  name="web",
  serve_cmd="yarn nx run web:serve",
  allow_parallel=True,
  serve_env={},
  labels=['services'],
  resource_deps=['Yarn Install', 'main']
)
